#config_version=5


#### Hardware Boards

hardware:
    platform: p3_roc

p_roc:
    driverboards: pdb
    use_watchdog: true
    watchdog_time: 1s

#### Virtual Controls & Settings

keyboard:
    z:
        switch: s_left_flipper
    "/":
        switch: s_right_flipper
    1:
        switch: s_trough_1
        toggle: true
    2:
        switch: s_trough_2
        toggle: true
    3:
        switch: s_trough_3
        toggle: true
    4:
        switch: s_trough_4
        toggle: true
    5:
        switch: s_trough_5
        toggle: true
    6:
        switch: s_trough_6
        toggle: true
    7:
        switch: s_trough_7
        toggle: true
    8:
        switch: s_trough_8
        toggle: true
    p:
        switch: s_plunger
    s: 
        switch: s_start

virtual_platform_start_active_switches:
    s_trough_1,
    s_trough_2,
    s_trough_3,
    s_trough_4,
    s_trough_5,
    s_trough_6,
    s_trough_7,
    s_trough_8


#### Media & Display

displays:
    window:
      width: 800
      height: 600

slides:
    welcome_slide:
        widgets:
          - type: text
            text: PINBALL!
            font_size: 50
            color: yellow
    attract_started:
        widgets:
          - type: text
            text: Fucking play me!!
            font_size: 70
            color: green
    ball_started:
        widgets:
            type: text
            text: PLAYER (number) BALL (ball)

slide_player:
    init_done: welcome_slide
    mode_attract_started: attract_started
    mode_game_started: ball_started

#### Switches/Coils

playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger

switches:
    # -- Flippers
    s_left_flipper:
        number: A0-B1-5
        tags: left_flipper
    s_right_flipper:
        number: A0-B1-7
        tags: right_flipper
    
    # COMMENTED OUT TO DEPLOY WE NEED REAL NUMBERS #
    # # -- Ball Trough TODO: Switch numbers.
    # s_trough_1:
    #     number: 
    # s_trough_2:
    #     number: 
    # s_trough_3:
    #     number: 
    # s_trough_4:
    #     number: 
    # s_trough_5:
    #     number: 
    # s_trough_6:
    #     number: 
    # s_trough_7:
    #     number: 
    # s_trough_8:
    #     number: 
    # s_trough_jam:
    #     number: 

    # # -- Plunger
    # s_plunger:
    #     number: 

    # # -- User Buttons
    # s_start:
    #     number:
    #     tags: start

coils:
    c_flipper_left:
        number: A0-B1-6
        allow_enable: true
        default_hold_power: 0.125
        default_pulse_ms: 20
    c_flipper_right:
        number: A0-B1-4
        allow_enable: true
        default_hold_power: 0.125
        default_pulse_ms: 20

    # -- Ball Trough TODO: coil number
    c_trough_eject:
        number: 
        default_pulse_ms: 20

    c_plunger_eject:
        number:
        default_pulse_ms: 20

# -- Flipper Controls
flippers:
    left_flipper:
        main_coil: c_flipper_left
        activation_switch: s_left_flipper
        enable_events: machine_reset_phase_3 # TODO TEMP, WE WILL CHANGE THIS WHEN WE ADD A START GAME!
    right_flipper:
        main_coil: c_flipper_right
        activation_switch: s_right_flipper
        enable_events: machine_reset_phase_3 # TODO TEMP, WE WILL CHANGE THIS WHEN WE ADD A START GAME!

# -- Ball Trough Controls
ball_devices:
    bd_trough:
        ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_5, s_trough_6, s_trough_7, s_trough_8
        eject_coil: c_trough_eject
        tags: trough, home, drain
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 15ms 
        eject_targets: bd_plunger
        debug: yes

    # bd_plunger is a placeholder just so the trough's eject_targets are valid
    bd_plunger:
        ball_switches: s_plunger
        mechanical_eject: true
        eject_coil: c_plunger_eject
        eject_timeouts: 3s
        debug: yes

