#config_version=5


#### Hardware Boards

hardware:
    platform: p3_roc

p_roc:
    driverboards: pdb
    use_watchdog: true
    watchdog_time: 1s

#### Virtual Controls & Settings

keyboard:
    z:
        switch: s_left_flipper
    "/":
        switch: s_right_flipper
    1:
        switch: s_trough_1
        toggle: true
    p:
        switch: s_plunger
    s: 
        switch: s_start

virtual_platform_start_active_switches:
    s_trough_1


#### Media & Display

displays:
    window:
      width: 800
      height: 600

slides:
    welcome_slide:
        widgets:
          - type: text
            text: PINBALL!
            font_size: 50
            color: yellow
    attract_started:
        widgets:
          - type: text
            text: Fucking play me!!
            font_size: 70
            color: green
    ball_started:
        widgets:
            type: text
            text: PLAYER (number) BALL (ball)

slide_player:
    init_done: welcome_slide
    mode_attract_started: attract_started
    mode_game_started: ball_started

#### Switches/Coils

playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger


## EVERYTHING APPEARS TO BE OFF BY 2, real pin 7 is "5" ##
switches:
    
    placeholder_b: 
        number: A0-B1-2
    placeholder_c: 
        number: A0-B1-4
    
    # -- Random components
    s_subway_eject: 
        number: A0-B1-6
    
    # -- Flippers
    s_left_flipper:
        number: A0-B1-3   # ACTUAL 5
        tags: left_flipper
    s_right_flipper:
        number: A0-B1-5   # ACTUAL 7
        tags: right_flipper

    # -- Plunger
    s_plunger:
        number: A0-B1-1
        tags: plunger

    # -- Ball Trough 
    s_trough_1: 
        number: A0-B0-6
        type: NC

    s_trough_jam:
        number: A0-B0-7
        type: NC

    # -- User Buttons
    s_start:
        number: A0-B1-7
        tags: start
        

coils:
    # -- Flippers
    c_flipper_left:
        number: A1-B1-4
        allow_enable: true
        default_hold_power: 0.125
        default_pulse_ms: 20
    c_flipper_right:
        number: A1-B1-2
        allow_enable: true
        default_hold_power: 0.125
        default_pulse_ms: 20

    # -- Ball Trough
    c_trough_eject:
        number: A1-B1-1
        default_pulse_ms: 20

    c_plunger_eject:
        number: A1-B1-0
        default_pulse_ms: 20

    # -- Random components
    c_subway_eject:
        number: A1-B1-6

# -- Flipper Controls
flippers:
    left_flipper:
        main_coil: c_flipper_left
        activation_switch: s_left_flipper

    right_flipper:
        main_coil: c_flipper_right
        activation_switch: s_right_flipper

# -- Ball Trough Controls
ball_devices:
    bd_trough:
        ball_switches: s_trough_1, s_trough_jam
        eject_coil: c_trough_eject
        eject_coil_jam_pulse: 15ms
        jam_switch: s_trough_jam
        eject_targets: bd_plunger
        tags: trough, home, drain
        debug: yes

    bd_plunger:
        ball_switches: s_plunger
        eject_coil: c_plunger_eject
        eject_timeouts: 3s
        debug: yes

    bd_subway_vuk:
        ball_switches: s_subway_eject
        eject_coil: c_subway_eject
        debug: yes

