#config_version=5
##! mode: skillshot

mode:
    start_events: start_skillshot
    stop_events: stop_skillshot, s_spinner_active, s_left_orbit_inactive, s_right_rollover_active, s_left_rollover_active, s_center_rollover_active
    priority: 105
    restart_on_next_ball: True

slide_player:
  mode_skillshot_started:
    widgets:
      - type: text
        text: USE YOUR SKILLZZZ
        font_size: 200