#config_version=5
##! mode: skillshot

mode:
    start_events: ball_started
    stop_events: s_spinner_active, s_left_orbit_inactive, s_right_rollover_active, s_left_rollover_active, s_center_rollover_active
    priority: 105
    restart_on_next_ball: True

slide_player:
  mode_skillshot_started:
    widgets:
      - type: text
        text: Hit The Skillshot!
        font_size: 100

variable_player:
    s_spinner_active:
        score: 100
    s_left_orbit_inactive:
        score: 200
    s_right_rollover_active:
        score: 300
    s_left_rollover_active:
        score: 400
    s_center_rollover_active:
        score: 500